// Generated by CoffeeScript 1.10.0
(function() {
  var Server, http, server;

  Server = require('ws').Server;

  http = require("http");

  server = new Server({
    port: 8080
  });

  server.on('connection', function(ws) {
    console.log('module connected');
    return ws.on('message', function(message) {
      return console.log('received: %s', message);
    });
  });

}).call(this);

//# sourceMappingURL=main.js.map
